---
abstract: 'Sane APIs for IP addresses and networks'
author:
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Greg Oschwald <oschwald@cpan.org>'
  - 'Olaf Alders <oalders@wundercounter.com>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Works
requires:
  Carp: 0
  Exporter: 0
  List::AllUtils: 0
  Math::Int128: 0.06
  Moo: 0
  Moo::Role: 0
  Scalar::Util: 0
  Socket: 1.99
  Sub::Quote: 0
  integer: 0
  namespace::autoclean: 0
  overload: 0
  perl: 5.010000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/maxmind/Net-Works/issues
  repository: git://github.com/maxmind/Net-Works.git
version: 0.15
x_authority: cpan:DROLSKY
x_contributors:
  - 'Alexander Hartmaier <abraxxa@cpan.org>'
  - 'TJ Mather <tjmather@maxmind.com>'
  - 'William Stevenson <wstevenson@maxmind.com>'
