---
abstract: 'Sane APIs for IP addresses and networks'
author:
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Olaf Alders <olaf@wundercounter.com>'
  - 'Greg Oschwald <oschwald@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Works
requires:
  Carp: 0
  Exporter: 0
  List::AllUtils: 0
  Math::Int128: 0.06
  Moose: 0
  Moose::Role: 0
  MooseX::Types: 0
  MooseX::Types::Combine: 0
  MooseX::Types::Moose: 0
  Scalar::Util: 0
  Socket: 1.99
  integer: 0
  namespace::autoclean: 0
  overload: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-Works
  repository: git://github.com/maxmind/Net-Works.git
version: 0.07
x_authority: cpan:DROLSKY
